name: Déploiement Streamlit sur EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Configuration de Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Installation des dépendances
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Lancement des tests
      run: |
        source venv/bin/activate
        python -m unittest discover -s test_login

    - name: Copie des fichiers sur le serveur EC2
      run: |
        scp -r -o StrictHostKeyChecking=no -i ~/.ssh/ec2_private_key.pem deploy_files/* ubuntu@${{ secrets.EC2_HOST }}:~/immobilier_en_france/

    - name: Arrêt de l'ancienne instance Streamlit
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_private_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
        pkill -f streamlit || echo "Pas d'instance en cours"
        sleep 3
        EOF

    - name: Lancement de l'application
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_private_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
        cd ~/immobilier_en_france/
        echo "Vérification de la présence du fichier main.py"
        ls -l main.py

        echo "Démarrage de Streamlit en arrière-plan..."
        nohup venv/bin/python -m streamlit run main.py --server.port 8501 --server.enableCORS false > output.log 2>&1 &
        echo "Application Streamlit relancée."
        EOF