name: Test SSH Connection

on:
  workflow_dispatch: # Permet de déclencher manuellement le workflow

jobs:
  test_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Configuration des clés SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/ec2_private_key.pem
          chmod 400 ~/.ssh/ec2_private_key.pem
          echo -e "Host ${{ secrets.EC2_HOST }}\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

      - name: Test de la connexion SSH
        run: ssh -T ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} -o ConnectTimeout=10
